-- =====================================================================
--  NMBR — OPTIONAL DEMONSTRATION DATA  (fictional, for training only)
--
--  Run NMBR-supabase-setup.sql FIRST, then run this file the same way
--  (SQL Editor -> paste -> Run). It loads 12 barangays and 160 fictional
--  members with deliberate duplicate cases so staff can practise.
--
--  Do NOT run this on a database that already holds real resident records.
--  It is idempotent, so a second run changes nothing.
-- =====================================================================

-- =====================================================================
-- NMBR — supabase/seed.sql
-- FICTIONAL demonstration dataset for Nabua, Camarines Sur.
-- Run AFTER the migrations, in the Supabase SQL editor.
--   • 12 barangays
--   • 160 master person records
--   • 15 duplicate cases (pending + resolved)
-- Re-running is safe: it skips rows that already exist.
-- =====================================================================

-- 1. Barangays
insert into barangays (name, municipality, province, district)
values
  ('San Isidro', 'Nabua', 'Camarines Sur', 'Poblacion'),
  ('San Roque', 'Nabua', 'Camarines Sur', 'Poblacion'),
  ('La Purisima', 'Nabua', 'Camarines Sur', 'Poblacion'),
  ('Sagrada Familia', 'Nabua', 'Camarines Sur', 'Poblacion'),
  ('San Antonio', 'Nabua', 'Camarines Sur', 'North'),
  ('San Juan', 'Nabua', 'Camarines Sur', 'North'),
  ('San Nicolas', 'Nabua', 'Camarines Sur', 'East'),
  ('Santa Cruz', 'Nabua', 'Camarines Sur', 'East'),
  ('San Miguel', 'Nabua', 'Camarines Sur', 'South'),
  ('San Rafael', 'Nabua', 'Camarines Sur', 'South'),
  ('Sto. Domingo', 'Nabua', 'Camarines Sur', 'West'),
  ('San Pedro', 'Nabua', 'Camarines Sur', 'West')
on conflict (municipality, name) do nothing;

-- 2. Staff accounts (profiles only).
--    Supabase Auth accounts are created separately — see supabase/PROVISION_USERS.sql
insert into users (name, email, role)
values
  ('Engr. Ramon Villaflor', 'admin@nabua.gov.ph', 'SYSTEM_ADMIN'),
  ('Maria Santos', 'maria.santos@nabua.gov.ph', 'ADMINISTRATOR'),
  ('Josefina Ramos', 'josefina.ramos@nabua.gov.ph', 'ADMINISTRATOR'),
  ('Pedro Reyes', 'pedro.reyes@nabua.gov.ph', 'ENCODER'),
  ('Ana Villanueva', 'ana.villanueva@nabua.gov.ph', 'ENCODER'),
  ('Liza Mercado', 'liza.mercado@nabua.gov.ph', 'ENCODER'),
  ('Cornelio Bautista', 'viewer@nabua.gov.ph', 'VIEWER')
on conflict (email) do nothing;

-- 3. Households
insert into households (household_no, barangay_id, purok, address)
select v.no, b.id, v.purok, v.purok || ', ' || b.name || ', Nabua, Camarines Sur'
from (values
  ('HH-2026-0001', 'San Antonio', 'Purok 1'),
  ('HH-2026-0002', 'San Juan', 'Sitio Iraya'),
  ('HH-2026-0003', 'Sagrada Familia', 'Purok 5'),
  ('HH-2026-0004', 'Sagrada Familia', 'Purok 5'),
  ('HH-2026-0005', 'San Nicolas', 'Purok 7'),
  ('HH-2026-0006', 'San Isidro', 'Purok 4'),
  ('HH-2026-0007', 'Sagrada Familia', 'Purok 6'),
  ('HH-2026-0008', 'Sto. Domingo', 'Purok 1'),
  ('HH-2026-0009', 'Sagrada Familia', 'Purok 1'),
  ('HH-2026-0010', 'Sagrada Familia', 'Purok 2'),
  ('HH-2026-0011', 'La Purisima', 'Purok 6'),
  ('HH-2026-0012', 'San Isidro', 'Purok 7')
) as v(no, barangay, purok)
join barangays b on b.name = v.barangay
on conflict (household_no) do nothing;

-- 4. Master person records.
--    identity_lock = false keeps the exact demonstration identity keys, including
--    the "#2" discriminators that represent verified namesakes.
insert into persons (
  reference_no, first_name, middle_name, last_name, suffix, date_of_birth, sex, civil_status,
  contact_number, address, purok, barangay_id, status, remarks, identity_key, identity_lock,
  created_by, created_at, updated_at)
select v.reference_no, v.first_name, v.middle_name, v.last_name, v.suffix, v.date_of_birth, v.sex,
       v.civil_status, v.contact_number, v.address, v.purok, b.id, v.status::person_status, v.remarks,
       v.identity_key, v.identity_lock, u.id, v.created_at, v.updated_at
from (values
  ('NMBR-002417', 'Rowena', 'Marquez', 'Villanueva', null,
    date '1942-05-18', 'FEMALE', 'MARRIED',
    '09753608569', 'Purok 3, Sto. Domingo, Nabua, Camarines Sur', 'Purok 3', 'Sto. Domingo',
    'INACTIVE', null, 'VILLANUEVA|ROWENA|MARQUEZ||1942-05-18', true,
    'liza.mercado@nabua.gov.ph', now() - interval '194 days', now() - interval '2 days'),
  ('NMBR-002418', 'Benjamin', 'Cruz', 'Gumabao', null,
    date '1934-01-11', 'MALE', 'SEPARATED',
    '09322791398', 'Purok 6, San Antonio, Nabua, Camarines Sur', 'Purok 6', 'San Antonio',
    'ACTIVE', null, 'GUMABAO|BENJAMIN|CRUZ||1934-01-11', true,
    'liza.mercado@nabua.gov.ph', now() - interval '150 days', now() - interval '5 days'),
  ('NMBR-002419', 'Juan', 'Bermudo', 'Ocampo', null,
    date '1976-12-15', 'MALE', 'SEPARATED',
    null, 'Purok 2, San Juan, Nabua, Camarines Sur', 'Purok 2', 'San Juan',
    'INACTIVE', null, 'OCAMPO|JUAN|BERMUDO||1976-12-15', true,
    'liza.mercado@nabua.gov.ph', now() - interval '301 days', now() - interval '12 days'),
  ('NMBR-002420', 'Danilo', null, 'Sarmiento', null,
    date '1999-06-06', 'MALE', 'SINGLE',
    '09696549298', 'Sitio Ilawod, San Rafael, Nabua, Camarines Sur', 'Sitio Ilawod', 'San Rafael',
    'ACTIVE', null, 'SARMIENTO|DANILO|||1999-06-06', true,
    'liza.mercado@nabua.gov.ph', now() - interval '187 days', now() - interval '23 days'),
  ('NMBR-002421', 'Antonio', 'Navarro', 'Sarmiento', null,
    date '1994-09-14', 'MALE', 'SEPARATED',
    '09525526639', 'Purok 1, San Juan, Nabua, Camarines Sur', 'Purok 1', 'San Juan',
    'ACTIVE', null, 'SARMIENTO|ANTONIO|NAVARRO||1994-09-14', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '189 days', now() - interval '16 days'),
  ('NMBR-002422', 'Emmanuel', 'Aquino', 'Reyes', 'Sr.',
    date '1950-07-27', 'MALE', 'MARRIED',
    '09444164205', 'Purok 4, La Purisima, Nabua, Camarines Sur', 'Purok 4', 'La Purisima',
    'ACTIVE', null, 'REYES|EMMANUEL|AQUINO|SR|1950-07-27', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '43 days', now() - interval '1 days'),
  ('NMBR-002423', 'Rodel', 'Padilla', 'Reyes', null,
    date '1957-06-04', 'MALE', 'WIDOWED',
    '09607846942', 'Purok 2, San Rafael, Nabua, Camarines Sur', 'Purok 2', 'San Rafael',
    'ACTIVE', null, 'REYES|RODEL|PADILLA||1957-06-04', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '399 days', now() - interval '6 days'),
  ('NMBR-002424', 'Ana', 'Tolentino', 'Bautista', 'III',
    date '1934-01-22', 'FEMALE', 'WIDOWED',
    '09565462230', 'Purok 2, Sagrada Familia, Nabua, Camarines Sur', 'Purok 2', 'Sagrada Familia',
    'ACTIVE', null, 'BAUTISTA|ANA|TOLENTINO|III|1934-01-22', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '373 days', now() - interval '8 days'),
  ('NMBR-002425', 'Evelyn', null, 'Fernandez', null,
    date '1937-09-12', 'FEMALE', 'SINGLE',
    '534-236', 'Sitio Iraya, Sagrada Familia, Nabua, Camarines Sur', 'Sitio Iraya', 'Sagrada Familia',
    'ACTIVE', null, 'FERNANDEZ|EVELYN|||1937-09-12', true,
    'liza.mercado@nabua.gov.ph', now() - interval '519 days', now() - interval '24 days'),
  ('NMBR-002426', 'Nestor', 'Mercado', 'Dela Cruz', null,
    date '1971-08-07', 'MALE', 'WIDOWED',
    '09972001086', 'Purok 5, San Pedro, Nabua, Camarines Sur', 'Purok 5', 'San Pedro',
    'ACTIVE', null, 'DELA CRUZ|NESTOR|MERCADO||1971-08-07', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '451 days', now() - interval '18 days'),
  ('NMBR-002427', 'Juan', 'Gonzales', 'Dacillo', null,
    date '1957-09-14', 'MALE', 'MARRIED',
    '09288616835', 'Purok 5, Santa Cruz, Nabua, Camarines Sur', 'Purok 5', 'Santa Cruz',
    'ACTIVE', null, 'DACILLO|JUAN|GONZALES||1957-09-14', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '389 days', now() - interval '13 days'),
  ('NMBR-002428', 'Marilou', 'Cruz', 'Enciso', null,
    date '1968-02-08', 'FEMALE', 'MARRIED',
    '571-147', 'Sitio Ilawod, Sto. Domingo, Nabua, Camarines Sur', 'Sitio Ilawod', 'Sto. Domingo',
    'ACTIVE', null, 'ENCISO|MARILOU|CRUZ||1968-02-08', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '266 days', now() - interval '19 days'),
  ('NMBR-002429', 'Bernadette', 'Tolentino', 'Santos', null,
    date '1997-10-01', 'FEMALE', 'MARRIED',
    '09277810208', 'Purok 3, Sagrada Familia, Nabua, Camarines Sur', 'Purok 3', 'Sagrada Familia',
    'INACTIVE', null, 'SANTOS|BERNADETTE|TOLENTINO||1997-10-01', true,
    'liza.mercado@nabua.gov.ph', now() - interval '429 days', now() - interval '29 days'),
  ('NMBR-002430', 'Ryan', 'Santos', 'Orobia', null,
    null, 'MALE', 'MARRIED',
    '09739875145', 'Purok 4, Sagrada Familia, Nabua, Camarines Sur', 'Purok 4', 'Sagrada Familia',
    'ACTIVE', null, 'OROBIA|RYAN|SANTOS||', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '226 days', now() - interval '18 days'),
  ('NMBR-002431', 'Rafael', 'Cruz', 'Bautista', null,
    date '1969-09-11', 'MALE', 'SEPARATED',
    '734-909', 'Purok 7, La Purisima, Nabua, Camarines Sur', 'Purok 7', 'La Purisima',
    'INACTIVE', null, 'BAUTISTA|RAFAEL|CRUZ||1969-09-11', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '133 days', now() - interval '19 days'),
  ('NMBR-002432', 'Catherine', 'Castillo', 'Gonzales', null,
    date '1945-12-06', 'FEMALE', 'SINGLE',
    '09211356775', 'Purok 4, San Pedro, Nabua, Camarines Sur', 'Purok 4', 'San Pedro',
    'ACTIVE', null, 'GONZALES|CATHERINE|CASTILLO||1945-12-06', true,
    'liza.mercado@nabua.gov.ph', now() - interval '47 days', now() - interval '1 days'),
  ('NMBR-002433', 'Pedro', 'Castillo', 'Baldovino', 'Jr.',
    date '2014-04-09', 'MALE', 'SINGLE',
    '09113040216', 'Sitio Balongay, La Purisima, Nabua, Camarines Sur', 'Sitio Balongay', 'La Purisima',
    'ACTIVE', null, 'BALDOVINO|PEDRO|CASTILLO|JR|2014-04-09', true,
    'liza.mercado@nabua.gov.ph', now() - interval '459 days', now() - interval '7 days'),
  ('NMBR-002434', 'Sheila', 'Imperial', 'Baldovino', null,
    date '1990-03-15', 'FEMALE', 'SINGLE',
    '09388262631', 'Purok 2, San Antonio, Nabua, Camarines Sur', 'Purok 2', 'San Antonio',
    'ACTIVE', null, 'BALDOVINO|SHEILA|IMPERIAL||1990-03-15', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '217 days', now() - interval '17 days'),
  ('NMBR-002435', 'Rodel', 'Rivera', 'Sarmiento', null,
    date '1953-10-18', 'MALE', 'MARRIED',
    null, 'Sitio Iraya, San Nicolas, Nabua, Camarines Sur', 'Sitio Iraya', 'San Nicolas',
    'ACTIVE', null, 'SARMIENTO|RODEL|RIVERA||1953-10-18', true,
    'liza.mercado@nabua.gov.ph', now() - interval '106 days', now() - interval '27 days'),
  ('NMBR-002436', 'Perlita', 'Aquino', 'Navarro', null,
    date '2024-12-06', 'FEMALE', 'SINGLE',
    '09895411840', 'Purok 1, San Miguel, Nabua, Camarines Sur', 'Purok 1', 'San Miguel',
    'ACTIVE', null, 'NAVARRO|PERLITA|AQUINO||2024-12-06', true,
    'liza.mercado@nabua.gov.ph', now() - interval '63 days', now() - interval '22 days'),
  ('NMBR-002437', 'Gloria', 'Salvador', 'Dela Cruz', null,
    null, 'FEMALE', 'SINGLE',
    '09592702965', 'Purok 6, San Miguel, Nabua, Camarines Sur', 'Purok 6', 'San Miguel',
    'ACTIVE', null, 'DELA CRUZ|GLORIA|SALVADOR||', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '433 days', now() - interval '0 days'),
  ('NMBR-002438', 'Ana', 'Villanueva', 'Tolentino', null,
    date '1967-07-09', 'FEMALE', 'MARRIED',
    null, 'Purok 1, San Roque, Nabua, Camarines Sur', 'Purok 1', 'San Roque',
    'ACTIVE', null, 'TOLENTINO|ANA|VILLANUEVA||1967-07-09', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '242 days', now() - interval '11 days'),
  ('NMBR-002439', 'Rodel', 'Mercado', 'Albao', null,
    date '1992-10-04', 'MALE', 'SEPARATED',
    null, 'Purok 1, San Nicolas, Nabua, Camarines Sur', 'Purok 1', 'San Nicolas',
    'ACTIVE', null, 'ALBAO|RODEL|MERCADO||1992-10-04', true,
    'liza.mercado@nabua.gov.ph', now() - interval '259 days', now() - interval '30 days'),
  ('NMBR-002440', 'Marilou', 'Ramos', 'Reyes', null,
    date '2000-09-06', 'FEMALE', 'SINGLE',
    '09818078678', 'Sitio Iraya, San Isidro, Nabua, Camarines Sur', 'Sitio Iraya', 'San Isidro',
    'ACTIVE', null, 'REYES|MARILOU|RAMOS||2000-09-06', true,
    'liza.mercado@nabua.gov.ph', now() - interval '357 days', now() - interval '5 days'),
  ('NMBR-002441', 'Antonio', 'Reyes', 'Halcon', null,
    date '2011-08-27', 'MALE', 'SINGLE',
    null, 'Purok 5, San Nicolas, Nabua, Camarines Sur', 'Purok 5', 'San Nicolas',
    'ACTIVE', null, 'HALCON|ANTONIO|REYES||2011-08-27', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '108 days', now() - interval '17 days'),
  ('NMBR-002442', 'Mario', 'Salvador', 'Ocampo', null,
    date '2003-04-18', 'MALE', 'SEPARATED',
    '09132304967', 'Sitio Iraya, San Rafael, Nabua, Camarines Sur', 'Sitio Iraya', 'San Rafael',
    'ACTIVE', null, 'OCAMPO|MARIO|SALVADOR||2003-04-18', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '183 days', now() - interval '14 days'),
  ('NMBR-002443', 'Jose', 'Fernandez', 'Rivera', null,
    date '1958-03-07', 'MALE', 'SEPARATED',
    '09967737641', 'Purok 3, San Rafael, Nabua, Camarines Sur', 'Purok 3', 'San Rafael',
    'ACTIVE', null, 'RIVERA|JOSE|FERNANDEZ||1958-03-07', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '399 days', now() - interval '12 days'),
  ('NMBR-002444', 'Bernadette', 'Santos', 'Cordial', null,
    date '1996-10-02', null, 'SINGLE',
    '09498211145', 'Purok 3, San Isidro, Nabua, Camarines Sur', 'Purok 3', 'San Isidro',
    'ACTIVE', null, 'CORDIAL|BERNADETTE|SANTOS||1996-10-02', true,
    'liza.mercado@nabua.gov.ph', now() - interval '457 days', now() - interval '30 days'),
  ('NMBR-002445', 'Jocelyn', null, 'Castillo', null,
    date '1996-01-16', 'FEMALE', 'SEPARATED',
    '09581844221', 'Sitio Ilawod, San Antonio, Nabua, Camarines Sur', 'Sitio Ilawod', 'San Antonio',
    'ACTIVE', null, 'CASTILLO|JOCELYN|||1996-01-16', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '193 days', now() - interval '24 days'),
  ('NMBR-002446', 'Dennis', 'Ramos', 'Laguardia', null,
    date '2020-04-10', 'MALE', 'SINGLE',
    '09198652092', 'Purok 1, San Rafael, Nabua, Camarines Sur', 'Purok 1', 'San Rafael',
    'ACTIVE', null, 'LAGUARDIA|DENNIS|RAMOS||2020-04-10', true,
    'liza.mercado@nabua.gov.ph', now() - interval '484 days', now() - interval '30 days'),
  ('NMBR-002447', 'Arlene', 'Bautista', 'Velasco', 'Sr.',
    date '1943-08-27', 'FEMALE', 'WIDOWED',
    '09442747606', 'Purok 4, Sto. Domingo, Nabua, Camarines Sur', 'Purok 4', 'Sto. Domingo',
    'ACTIVE', null, 'VELASCO|ARLENE|BAUTISTA|SR|1943-08-27', true,
    'liza.mercado@nabua.gov.ph', now() - interval '365 days', now() - interval '0 days'),
  ('NMBR-002448', 'Arnold', 'Navarro', 'Reyes', null,
    null, 'MALE', 'SINGLE',
    '09297356218', 'Purok 7, Santa Cruz, Nabua, Camarines Sur', 'Purok 7', 'Santa Cruz',
    'ACTIVE', null, 'REYES|ARNOLD|NAVARRO||', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '223 days', now() - interval '5 days'),
  ('NMBR-002449', 'Chona', 'Tolentino', 'Enciso', 'Jr.',
    null, 'FEMALE', 'SEPARATED',
    null, 'Purok 3, San Juan, Nabua, Camarines Sur', 'Purok 3', 'San Juan',
    'ACTIVE', null, 'ENCISO|CHONA|TOLENTINO|JR|', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '238 days', now() - interval '10 days'),
  ('NMBR-002450', 'Chona', 'Bermudo', 'Marquez', null,
    date '1937-08-03', 'FEMALE', 'WIDOWED',
    '09829909382', 'Sitio Balongay, Santa Cruz, Nabua, Camarines Sur', 'Sitio Balongay', 'Santa Cruz',
    'ACTIVE', null, 'MARQUEZ|CHONA|BERMUDO||1937-08-03', true,
    'liza.mercado@nabua.gov.ph', now() - interval '479 days', now() - interval '24 days'),
  ('NMBR-002451', 'Joel', null, 'Padilla', null,
    date '2009-12-18', 'MALE', 'SINGLE',
    '09917194892', 'Purok 5, San Isidro, Nabua, Camarines Sur', 'Purok 5', 'San Isidro',
    'ACTIVE', null, 'PADILLA|JOEL|||2009-12-18', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '57 days', now() - interval '12 days'),
  ('NMBR-002452', 'Josefina', 'Castillo', 'Kalaw', null,
    date '1978-07-02', 'FEMALE', 'MARRIED',
    '09834086712', 'Sitio Ilawod, San Isidro, Nabua, Camarines Sur', 'Sitio Ilawod', 'San Isidro',
    'ACTIVE', null, 'KALAW|JOSEFINA|CASTILLO||1978-07-02', true,
    'liza.mercado@nabua.gov.ph', now() - interval '442 days', now() - interval '10 days'),
  ('NMBR-002453', 'Joel', 'Imperial', 'Jalop', 'III',
    null, 'MALE', 'SINGLE',
    '09147075609', 'Sitio Balongay, Santa Cruz, Nabua, Camarines Sur', 'Sitio Balongay', 'Santa Cruz',
    'ACTIVE', null, 'JALOP|JOEL|IMPERIAL|III|', true,
    'liza.mercado@nabua.gov.ph', now() - interval '195 days', now() - interval '15 days'),
  ('NMBR-002454', 'Alfredo', 'Salvador', 'Aquino', null,
    date '2017-04-13', 'MALE', 'SINGLE',
    '09568216406', 'Purok 3, San Antonio, Nabua, Camarines Sur', 'Purok 3', 'San Antonio',
    'ACTIVE', null, 'AQUINO|ALFREDO|SALVADOR||2017-04-13', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '33 days', now() - interval '5 days'),
  ('NMBR-002455', 'Teresita', 'Rivera', 'Jalop', null,
    date '1943-05-27', 'FEMALE', 'WIDOWED',
    '09812718068', 'Sitio Iraya, Santa Cruz, Nabua, Camarines Sur', 'Sitio Iraya', 'Santa Cruz',
    'ACTIVE', null, 'JALOP|TERESITA|RIVERA||1943-05-27', true,
    'liza.mercado@nabua.gov.ph', now() - interval '215 days', now() - interval '11 days'),
  ('NMBR-002456', 'Rosario', 'Mercado', 'Aquino', 'III',
    date '1956-01-15', 'FEMALE', 'WIDOWED',
    '09896274929', 'Purok 6, San Roque, Nabua, Camarines Sur', 'Purok 6', 'San Roque',
    'ACTIVE', null, 'AQUINO|ROSARIO|MERCADO|III|1956-01-15', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '472 days', now() - interval '9 days'),
  ('NMBR-002457', 'Evelyn', 'Ocampo', 'Mercado', 'Jr.',
    date '1938-08-25', 'FEMALE', 'SEPARATED',
    '09948718813', 'Purok 5, Santa Cruz, Nabua, Camarines Sur', 'Purok 5', 'Santa Cruz',
    'ACTIVE', null, 'MERCADO|EVELYN|OCAMPO|JR|1938-08-25', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '396 days', now() - interval '11 days'),
  ('NMBR-002458', 'Antonio', 'Tolentino', 'Gumabao', 'Jr.',
    date '2010-06-10', 'MALE', 'SINGLE',
    '09943978946', 'Purok 1, San Nicolas, Nabua, Camarines Sur', 'Purok 1', 'San Nicolas',
    'ACTIVE', null, 'GUMABAO|ANTONIO|TOLENTINO|JR|2010-06-10', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '396 days', now() - interval '16 days'),
  ('NMBR-002459', 'Rodolfo', null, 'Orobia', 'Sr.',
    date '2021-12-19', 'MALE', 'SINGLE',
    '09502307951', 'Sitio Balongay, San Pedro, Nabua, Camarines Sur', 'Sitio Balongay', 'San Pedro',
    'ACTIVE', null, 'OROBIA|RODOLFO||SR|2021-12-19', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '529 days', now() - interval '4 days'),
  ('NMBR-002460', 'Arnold', 'Salvador', 'Isidro', 'Sr.',
    date '1959-09-22', 'MALE', 'SEPARATED',
    '09673650440', 'Sitio Balongay, San Nicolas, Nabua, Camarines Sur', 'Sitio Balongay', 'San Nicolas',
    'ACTIVE', null, 'ISIDRO|ARNOLD|SALVADOR|SR|1959-09-22', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '405 days', now() - interval '9 days'),
  ('NMBR-002461', 'Jhun', 'Fernandez', 'Sarmiento', null,
    date '1966-10-18', 'MALE', 'SINGLE',
    '09185577931', 'Sitio Balongay, Sagrada Familia, Nabua, Camarines Sur', 'Sitio Balongay', 'Sagrada Familia',
    'ACTIVE', null, 'SARMIENTO|JHUN|FERNANDEZ||1966-10-18', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '410 days', now() - interval '17 days'),
  ('NMBR-002462', 'Chona', 'Ramos', 'Bautista', 'Jr.',
    date '1939-07-24', 'FEMALE', 'WIDOWED',
    null, 'Purok 1, La Purisima, Nabua, Camarines Sur', 'Purok 1', 'La Purisima',
    'ACTIVE', null, 'BAUTISTA|CHONA|RAMOS|JR|1939-07-24', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '241 days', now() - interval '30 days'),
  ('NMBR-002463', 'Arlene', 'Bautista', 'Navarro', null,
    null, 'FEMALE', 'SINGLE',
    '09742022426', 'Purok 2, San Rafael, Nabua, Camarines Sur', 'Purok 2', 'San Rafael',
    'ACTIVE', null, 'NAVARRO|ARLENE|BAUTISTA||', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '474 days', now() - interval '13 days'),
  ('NMBR-002464', 'Elena', 'Marquez', 'Padilla', null,
    date '2023-10-12', 'FEMALE', 'SINGLE',
    '09502597194', 'Sitio Iraya, San Isidro, Nabua, Camarines Sur', 'Sitio Iraya', 'San Isidro',
    'ACTIVE', null, 'PADILLA|ELENA|MARQUEZ||2023-10-12', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '249 days', now() - interval '11 days'),
  ('NMBR-002465', 'Rodolfo', 'Rivera', 'Marquez', null,
    date '2023-04-10', 'MALE', 'SINGLE',
    '09887000306', 'Purok 6, Sagrada Familia, Nabua, Camarines Sur', 'Purok 6', 'Sagrada Familia',
    'ACTIVE', null, 'MARQUEZ|RODOLFO|RIVERA||2023-04-10', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '316 days', now() - interval '0 days'),
  ('NMBR-002466', 'Alvin', 'Reyes', 'Velasco', null,
    date '1984-03-05', 'MALE', 'MARRIED',
    null, 'Purok 7, San Rafael, Nabua, Camarines Sur', 'Purok 7', 'San Rafael',
    'ACTIVE', null, 'VELASCO|ALVIN|REYES||1984-03-05', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '225 days', now() - interval '13 days'),
  ('NMBR-002467', 'Alvin', 'Fernandez', 'Villanueva', null,
    date '1961-10-07', 'MALE', 'MARRIED',
    '09967505424', 'Purok 7, San Antonio, Nabua, Camarines Sur', 'Purok 7', 'San Antonio',
    'ACTIVE', null, 'VILLANUEVA|ALVIN|FERNANDEZ||1961-10-07', true,
    'liza.mercado@nabua.gov.ph', now() - interval '227 days', now() - interval '25 days'),
  ('NMBR-002468', 'Dennis', 'Rivera', 'Imperial', null,
    date '1953-08-24', 'MALE', 'MARRIED',
    '09764832694', 'Purok 3, La Purisima, Nabua, Camarines Sur', 'Purok 3', 'La Purisima',
    'ACTIVE', null, 'IMPERIAL|DENNIS|RIVERA||1953-08-24', true,
    'liza.mercado@nabua.gov.ph', now() - interval '292 days', now() - interval '6 days'),
  ('NMBR-002469', 'Nena', 'Bermudo', 'Rivera', null,
    date '2018-11-01', 'FEMALE', 'SINGLE',
    null, 'Purok 2, La Purisima, Nabua, Camarines Sur', 'Purok 2', 'La Purisima',
    'ACTIVE', null, 'RIVERA|NENA|BERMUDO||2018-11-01', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '400 days', now() - interval '22 days'),
  ('NMBR-002470', 'Alvin', 'Marquez', 'Aquino', null,
    date '1945-10-25', 'MALE', 'WIDOWED',
    '09472623636', 'Purok 1, San Roque, Nabua, Camarines Sur', 'Purok 1', 'San Roque',
    'ACTIVE', null, 'AQUINO|ALVIN|MARQUEZ||1945-10-25', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '336 days', now() - interval '15 days'),
  ('NMBR-002471', 'Alvin', 'Navarro', 'Bermudo', null,
    date '1945-02-11', 'MALE', 'MARRIED',
    '09211067880', 'Purok 1, San Juan, Nabua, Camarines Sur', 'Purok 1', 'San Juan',
    'ACTIVE', null, 'BERMUDO|ALVIN|NAVARRO||1945-02-11', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '229 days', now() - interval '23 days'),
  ('NMBR-002472', 'Elena', 'Cruz', 'Baldovino', null,
    date '1983-08-18', 'FEMALE', 'MARRIED',
    '09383539309', 'Sitio Iraya, Sto. Domingo, Nabua, Camarines Sur', 'Sitio Iraya', 'Sto. Domingo',
    'ACTIVE', null, 'BALDOVINO|ELENA|CRUZ||1983-08-18', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '429 days', now() - interval '5 days'),
  ('NMBR-002473', 'Lorna', 'Santos', 'Halcon', null,
    date '1992-09-25', 'FEMALE', 'SEPARATED',
    '09399840995', 'Sitio Iraya, San Pedro, Nabua, Camarines Sur', 'Sitio Iraya', 'San Pedro',
    'ACTIVE', null, 'HALCON|LORNA|SANTOS||1992-09-25', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '130 days', now() - interval '19 days'),
  ('NMBR-002474', 'Elena', 'Reyes', 'Macatangay', null,
    date '1992-01-14', 'FEMALE', 'SEPARATED',
    '09783147567', 'Purok 6, Sagrada Familia, Nabua, Camarines Sur', 'Purok 6', 'Sagrada Familia',
    'ACTIVE', null, 'MACATANGAY|ELENA|REYES||1992-01-14', true,
    'liza.mercado@nabua.gov.ph', now() - interval '172 days', now() - interval '21 days'),
  ('NMBR-002475', 'Rafael', 'Domingo', 'Dela Cruz', null,
    date '1978-08-07', 'MALE', 'WIDOWED',
    '09261442809', 'Sitio Balongay, San Isidro, Nabua, Camarines Sur', 'Sitio Balongay', 'San Isidro',
    'ACTIVE', null, 'DELA CRUZ|RAFAEL|DOMINGO||1978-08-07', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '172 days', now() - interval '9 days'),
  ('NMBR-002476', 'Jhun', 'Bonaobra', 'Villanueva', 'Sr.',
    date '1935-06-02', 'MALE', 'SINGLE',
    '09176954971', 'Purok 5, San Rafael, Nabua, Camarines Sur', 'Purok 5', 'San Rafael',
    'ACTIVE', null, 'VILLANUEVA|JHUN|BONAOBRA|SR|1935-06-02', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '386 days', now() - interval '9 days'),
  ('NMBR-002477', 'Rene', 'Cruz', 'Domingo', 'Sr.',
    null, 'MALE', 'SINGLE',
    '09318908098', 'Purok 1, San Antonio, Nabua, Camarines Sur', 'Purok 1', 'San Antonio',
    'INACTIVE', null, 'DOMINGO|RENE|CRUZ|SR|', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '48 days', now() - interval '8 days'),
  ('NMBR-002478', 'Ramon', 'Ramos', 'Fabregas', 'Sr.',
    date '1938-08-17', 'MALE', 'SINGLE',
    '09395796538', 'Purok 4, San Isidro, Nabua, Camarines Sur', 'Purok 4', 'San Isidro',
    'ACTIVE', null, 'FABREGAS|RAMON|RAMOS|SR|1938-08-17', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '195 days', now() - interval '8 days'),
  ('NMBR-002479', 'Lourdes', 'Domingo', 'Dela Cruz', 'Sr.',
    date '2002-06-26', 'FEMALE', 'SINGLE',
    '09609082556', 'Sitio Iraya, San Roque, Nabua, Camarines Sur', 'Sitio Iraya', 'San Roque',
    'DECEASED', null, 'DELA CRUZ|LOURDES|DOMINGO|SR|2002-06-26', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '516 days', now() - interval '16 days'),
  ('NMBR-002480', 'Arlene', 'Mercado', 'Albao', null,
    date '2008-09-19', 'FEMALE', 'SINGLE',
    '09438722935', 'Sitio Iraya, Sagrada Familia, Nabua, Camarines Sur', 'Sitio Iraya', 'Sagrada Familia',
    'ACTIVE', null, 'ALBAO|ARLENE|MERCADO||2008-09-19', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '384 days', now() - interval '3 days'),
  ('NMBR-002481', 'Bernadette', 'Mercado', 'Baldovino', 'Sr.',
    date '2021-04-27', 'FEMALE', 'SINGLE',
    '09953617022', 'Purok 4, Sagrada Familia, Nabua, Camarines Sur', 'Purok 4', 'Sagrada Familia',
    'ACTIVE', null, 'BALDOVINO|BERNADETTE|MERCADO|SR|2021-04-27', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '94 days', now() - interval '28 days'),
  ('NMBR-002482', 'Editha', 'Gonzales', 'Isidro', 'Jr.',
    date '2003-05-16', 'FEMALE', 'SEPARATED',
    '09976676330', 'Purok 7, Sagrada Familia, Nabua, Camarines Sur', 'Purok 7', 'Sagrada Familia',
    'ACTIVE', null, 'ISIDRO|EDITHA|GONZALES|JR|2003-05-16', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '362 days', now() - interval '8 days'),
  ('NMBR-002483', 'Teresita', null, 'Padilla', null,
    date '1988-06-10', 'FEMALE', 'SINGLE',
    null, 'Purok 7, San Rafael, Nabua, Camarines Sur', 'Purok 7', 'San Rafael',
    'ACTIVE', null, 'PADILLA|TERESITA|||1988-06-10', true,
    'liza.mercado@nabua.gov.ph', now() - interval '255 days', now() - interval '25 days'),
  ('NMBR-002484', 'Jose', 'Velasco', 'Rivera', null,
    date '2003-06-19', 'MALE', 'MARRIED',
    '09977501795', 'Sitio Ilawod, San Pedro, Nabua, Camarines Sur', 'Sitio Ilawod', 'San Pedro',
    'ACTIVE', null, 'RIVERA|JOSE|VELASCO||2003-06-19', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '377 days', now() - interval '21 days'),
  ('NMBR-002485', 'Lorna', 'Ocampo', 'Tolentino', null,
    date '1998-01-15', 'FEMALE', 'MARRIED',
    null, 'Purok 4, San Nicolas, Nabua, Camarines Sur', 'Purok 4', 'San Nicolas',
    'ACTIVE', null, 'TOLENTINO|LORNA|OCAMPO||1998-01-15', true,
    'liza.mercado@nabua.gov.ph', now() - interval '459 days', now() - interval '1 days'),
  ('NMBR-002486', 'Danilo', 'Navarro', 'Velasco', 'Sr.',
    date '1983-07-08', 'MALE', 'SEPARATED',
    '09125422734', 'Sitio Iraya, San Roque, Nabua, Camarines Sur', 'Sitio Iraya', 'San Roque',
    'ACTIVE', null, 'VELASCO|DANILO|NAVARRO|SR|1983-07-08', true,
    'liza.mercado@nabua.gov.ph', now() - interval '269 days', now() - interval '0 days'),
  ('NMBR-002487', 'Catherine', 'Salvador', 'Santos', null,
    date '1999-11-01', 'FEMALE', 'WIDOWED',
    '09648185841', 'Purok 7, San Miguel, Nabua, Camarines Sur', 'Purok 7', 'San Miguel',
    'ACTIVE', null, 'SANTOS|CATHERINE|SALVADOR||1999-11-01', true,
    'liza.mercado@nabua.gov.ph', now() - interval '389 days', now() - interval '9 days'),
  ('NMBR-002488', 'Christopher', 'Santos', 'Dela Cruz', 'Sr.',
    date '2021-10-18', 'MALE', 'SINGLE',
    '09643350051', 'Purok 2, San Antonio, Nabua, Camarines Sur', 'Purok 2', 'San Antonio',
    'ACTIVE', null, 'DELA CRUZ|CHRISTOPHER|SANTOS|SR|2021-10-18', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '46 days', now() - interval '16 days'),
  ('NMBR-002489', 'Lorna', 'Arellano', 'Reyes', null,
    date '1978-04-12', 'FEMALE', 'MARRIED',
    '989-446', 'Purok 7, San Isidro, Nabua, Camarines Sur', 'Purok 7', 'San Isidro',
    'ACTIVE', null, 'REYES|LORNA|ARELLANO||1978-04-12', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '265 days', now() - interval '11 days'),
  ('NMBR-002490', 'Alfredo', 'Sarmiento', 'Tolentino', null,
    date '1970-08-08', 'MALE', 'SINGLE',
    '09607307035', 'Sitio Balongay, San Isidro, Nabua, Camarines Sur', 'Sitio Balongay', 'San Isidro',
    'ACTIVE', null, 'TOLENTINO|ALFREDO|SARMIENTO||1970-08-08', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '470 days', now() - interval '21 days'),
  ('NMBR-002491', 'Cristina', 'Cruz', 'Bermudo', 'Sr.',
    date '1982-03-07', 'FEMALE', 'MARRIED',
    '09801691526', 'Purok 3, San Juan, Nabua, Camarines Sur', 'Purok 3', 'San Juan',
    'ACTIVE', null, 'BERMUDO|CRISTINA|CRUZ|SR|1982-03-07', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '77 days', now() - interval '9 days'),
  ('NMBR-002492', 'Ernesto', 'Navarro', 'Bautista', 'Sr.',
    date '2023-06-09', 'MALE', 'SINGLE',
    '09392457433', 'Sitio Ilawod, San Miguel, Nabua, Camarines Sur', 'Sitio Ilawod', 'San Miguel',
    'ACTIVE', null, 'BAUTISTA|ERNESTO|NAVARRO|SR|2023-06-09', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '258 days', now() - interval '18 days'),
  ('NMBR-002493', 'Chona', 'Villanueva', 'Salvador', null,
    date '2008-01-19', 'FEMALE', 'MARRIED',
    '09598182437', 'Purok 2, Sagrada Familia, Nabua, Camarines Sur', 'Purok 2', 'Sagrada Familia',
    'ACTIVE', null, 'SALVADOR|CHONA|VILLANUEVA||2008-01-19', true,
    'liza.mercado@nabua.gov.ph', now() - interval '253 days', now() - interval '23 days'),
  ('NMBR-002494', 'Arnold', 'Mercado', 'Isidro', null,
    date '1940-02-04', 'MALE', 'MARRIED',
    '09429701854', 'Purok 2, Santa Cruz, Nabua, Camarines Sur', 'Purok 2', 'Santa Cruz',
    'ACTIVE', null, 'ISIDRO|ARNOLD|MERCADO||1940-02-04', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '308 days', now() - interval '20 days'),
  ('NMBR-002495', 'Jose', 'Santos', 'Velasco', 'Sr.',
    date '1937-02-28', 'MALE', 'MARRIED',
    '272-942', 'Sitio Iraya, Santa Cruz, Nabua, Camarines Sur', 'Sitio Iraya', 'Santa Cruz',
    'ACTIVE', null, 'VELASCO|JOSE|SANTOS|SR|1937-02-28', true,
    'liza.mercado@nabua.gov.ph', now() - interval '303 days', now() - interval '3 days'),
  ('NMBR-002496', 'Rafael', 'Ramos', 'Domingo', null,
    date '2015-02-06', 'MALE', 'SINGLE',
    '09151807488', 'Sitio Iraya, Sagrada Familia, Nabua, Camarines Sur', 'Sitio Iraya', 'Sagrada Familia',
    'ACTIVE', null, 'DOMINGO|RAFAEL|RAMOS||2015-02-06', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '107 days', now() - interval '23 days'),
  ('NMBR-002497', 'Mario', null, 'Baldovino', null,
    date '1991-12-07', 'MALE', 'SINGLE',
    '09329963056', 'Sitio Ilawod, Santa Cruz, Nabua, Camarines Sur', 'Sitio Ilawod', 'Santa Cruz',
    'ACTIVE', null, 'BALDOVINO|MARIO|||1991-12-07', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '497 days', now() - interval '8 days'),
  ('NMBR-002498', 'Gloria', 'Sarmiento', 'Castillo', 'Sr.',
    date '1940-02-08', 'FEMALE', 'SINGLE',
    '09865200878', 'Purok 3, San Roque, Nabua, Camarines Sur', 'Purok 3', 'San Roque',
    'ACTIVE', null, 'CASTILLO|GLORIA|SARMIENTO|SR|1940-02-08', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '515 days', now() - interval '23 days'),
  ('NMBR-002499', 'Jose', 'Gonzales', 'Rivera', null,
    date '1975-09-02', 'MALE', 'WIDOWED',
    '09136877284', 'Purok 1, San Roque, Nabua, Camarines Sur', 'Purok 1', 'San Roque',
    'ACTIVE', null, 'RIVERA|JOSE|GONZALES||1975-09-02', true,
    'liza.mercado@nabua.gov.ph', now() - interval '91 days', now() - interval '29 days'),
  ('NMBR-002500', 'Ana', 'Arellano', 'Domingo', 'III',
    date '2015-01-17', 'FEMALE', 'SINGLE',
    null, 'Purok 3, San Nicolas, Nabua, Camarines Sur', 'Purok 3', 'San Nicolas',
    'ACTIVE', null, 'DOMINGO|ANA|ARELLANO|III|2015-01-17', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '50 days', now() - interval '29 days'),
  ('NMBR-002501', 'Carlos', 'Sarmiento', 'Gumabao', null,
    date '2007-09-25', 'MALE', 'SEPARATED',
    '09809001564', 'Purok 4, Sagrada Familia, Nabua, Camarines Sur', 'Purok 4', 'Sagrada Familia',
    'ACTIVE', null, 'GUMABAO|CARLOS|SARMIENTO||2007-09-25', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '481 days', now() - interval '14 days'),
  ('NMBR-002502', 'Ryan', 'Velasco', 'Padilla', 'Jr.',
    date '1988-10-15', 'MALE', 'MARRIED',
    '09734153411', 'Sitio Iraya, San Miguel, Nabua, Camarines Sur', 'Sitio Iraya', 'San Miguel',
    'ACTIVE', null, 'PADILLA|RYAN|VELASCO|JR|1988-10-15', true,
    'liza.mercado@nabua.gov.ph', now() - interval '123 days', now() - interval '17 days'),
  ('NMBR-002503', 'Wilfredo', 'Tolentino', 'Bautista', 'Sr.',
    null, 'MALE', 'SINGLE',
    '09275381367', 'Purok 1, Sagrada Familia, Nabua, Camarines Sur', 'Purok 1', 'Sagrada Familia',
    'ACTIVE', null, 'BAUTISTA|WILFREDO|TOLENTINO|SR|', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '213 days', now() - interval '26 days'),
  ('NMBR-002504', 'Rafael', 'Navarro', 'Jalop', 'Jr.',
    date '1940-02-06', 'MALE', 'MARRIED',
    '09869655010', 'Purok 5, Santa Cruz, Nabua, Camarines Sur', 'Purok 5', 'Santa Cruz',
    'ACTIVE', null, 'JALOP|RAFAEL|NAVARRO|JR|1940-02-06', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '77 days', now() - interval '21 days'),
  ('NMBR-002505', 'Benjamin', 'Ocampo', 'Arellano', null,
    date '2002-01-25', 'MALE', 'MARRIED',
    '09271662281', 'Purok 6, San Pedro, Nabua, Camarines Sur', 'Purok 6', 'San Pedro',
    'ACTIVE', null, 'ARELLANO|BENJAMIN|OCAMPO||2002-01-25', true,
    'liza.mercado@nabua.gov.ph', now() - interval '129 days', now() - interval '21 days'),
  ('NMBR-002506', 'Pedro', 'Marquez', 'Marquez', 'Sr.',
    date '2001-07-01', 'MALE', 'SINGLE',
    '09935435250', 'Purok 5, Santa Cruz, Nabua, Camarines Sur', 'Purok 5', 'Santa Cruz',
    'ACTIVE', null, 'MARQUEZ|PEDRO|MARQUEZ|SR|2001-07-01', true,
    'liza.mercado@nabua.gov.ph', now() - interval '357 days', now() - interval '19 days'),
  ('NMBR-002507', 'Aurora', 'Bautista', 'Arellano', null,
    date '1949-06-08', 'FEMALE', 'SINGLE',
    '09794315329', 'Purok 5, Santa Cruz, Nabua, Camarines Sur', 'Purok 5', 'Santa Cruz',
    'ACTIVE', null, 'ARELLANO|AURORA|BAUTISTA||1949-06-08', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '330 days', now() - interval '21 days'),
  ('NMBR-002508', 'Gloria', 'Ramos', 'Bermudo', null,
    date '1996-05-25', 'FEMALE', 'WIDOWED',
    '09901170168', 'Purok 3, Santa Cruz, Nabua, Camarines Sur', 'Purok 3', 'Santa Cruz',
    'ACTIVE', null, 'BERMUDO|GLORIA|RAMOS||1996-05-25', true,
    'liza.mercado@nabua.gov.ph', now() - interval '346 days', now() - interval '11 days'),
  ('NMBR-002509', 'Carlos', 'Fernandez', 'Aquino', 'Jr.',
    date '1960-11-15', 'MALE', 'SINGLE',
    '09925480096', 'Purok 4, San Rafael, Nabua, Camarines Sur', 'Purok 4', 'San Rafael',
    'ACTIVE', null, 'AQUINO|CARLOS|FERNANDEZ|JR|1960-11-15', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '31 days', now() - interval '18 days'),
  ('NMBR-002510', 'Aurora', null, 'Orobia', null,
    date '1978-08-19', 'FEMALE', 'MARRIED',
    '09439707025', 'Purok 1, Sto. Domingo, Nabua, Camarines Sur', 'Purok 1', 'Sto. Domingo',
    'ACTIVE', null, 'OROBIA|AURORA|||1978-08-19', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '254 days', now() - interval '20 days'),
  ('NMBR-002511', 'Antonio', 'Marquez', 'Ocampo', null,
    date '2016-07-09', 'MALE', 'SINGLE',
    '09159171897', 'Sitio Iraya, Sagrada Familia, Nabua, Camarines Sur', 'Sitio Iraya', 'Sagrada Familia',
    'ACTIVE', null, 'OCAMPO|ANTONIO|MARQUEZ||2016-07-09', true,
    'liza.mercado@nabua.gov.ph', now() - interval '426 days', now() - interval '12 days'),
  ('NMBR-002512', 'Chona', 'Rivera', 'Reyes', null,
    null, 'FEMALE', 'MARRIED',
    '09105628764', 'Purok 2, Sagrada Familia, Nabua, Camarines Sur', 'Purok 2', 'Sagrada Familia',
    'ACTIVE', null, 'REYES|CHONA|RIVERA||', true,
    'liza.mercado@nabua.gov.ph', now() - interval '7 days', now() - interval '16 days'),
  ('NMBR-002513', 'Dennis', 'Ocampo', 'Dacillo', null,
    date '1935-02-24', 'MALE', 'SEPARATED',
    '09454283546', 'Purok 1, Santa Cruz, Nabua, Camarines Sur', 'Purok 1', 'Santa Cruz',
    'ACTIVE', null, 'DACILLO|DENNIS|OCAMPO||1935-02-24', true,
    'liza.mercado@nabua.gov.ph', now() - interval '325 days', now() - interval '5 days'),
  ('NMBR-002514', 'Arlene', 'Ramos', 'Padilla', 'Jr.',
    date '1978-08-12', 'FEMALE', 'SINGLE',
    null, 'Purok 6, San Miguel, Nabua, Camarines Sur', 'Purok 6', 'San Miguel',
    'ACTIVE', null, 'PADILLA|ARLENE|RAMOS|JR|1978-08-12', true,
    'liza.mercado@nabua.gov.ph', now() - interval '202 days', now() - interval '19 days'),
  ('NMBR-002515', 'Winnie', 'Sarmiento', 'Castillo', 'III',
    date '1958-10-20', 'FEMALE', 'WIDOWED',
    '09707522339', 'Purok 2, Santa Cruz, Nabua, Camarines Sur', 'Purok 2', 'Santa Cruz',
    'ACTIVE', null, 'CASTILLO|WINNIE|SARMIENTO|III|1958-10-20', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '27 days', now() - interval '19 days'),
  ('NMBR-002516', 'Winnie', 'Fernandez', 'Ocampo', null,
    date '1974-07-18', 'FEMALE', 'SEPARATED',
    '09848425205', 'Purok 7, San Pedro, Nabua, Camarines Sur', 'Purok 7', 'San Pedro',
    'ACTIVE', null, 'OCAMPO|WINNIE|FERNANDEZ||1974-07-18', true,
    'liza.mercado@nabua.gov.ph', now() - interval '353 days', now() - interval '18 days'),
  ('NMBR-002517', 'Antonio', 'Reyes', 'Bermudo', null,
    date '1998-11-23', 'MALE', 'SINGLE',
    null, 'Purok 4, San Juan, Nabua, Camarines Sur', 'Purok 4', 'San Juan',
    'DECEASED', null, 'BERMUDO|ANTONIO|REYES||1998-11-23', true,
    'liza.mercado@nabua.gov.ph', now() - interval '277 days', now() - interval '21 days'),
  ('NMBR-002518', 'Ramon', 'Fernandez', 'Jalop', 'III',
    date '2021-07-20', 'MALE', 'SINGLE',
    null, 'Sitio Balongay, La Purisima, Nabua, Camarines Sur', 'Sitio Balongay', 'La Purisima',
    'ACTIVE', null, 'JALOP|RAMON|FERNANDEZ|III|2021-07-20', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '258 days', now() - interval '3 days'),
  ('NMBR-002519', 'Fernando', 'Gonzales', 'Aquino', null,
    date '1993-09-21', 'MALE', 'SINGLE',
    '09621675269', 'Purok 3, San Rafael, Nabua, Camarines Sur', 'Purok 3', 'San Rafael',
    'ACTIVE', null, 'AQUINO|FERNANDO|GONZALES||1993-09-21', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '90 days', now() - interval '23 days'),
  ('NMBR-002520', 'Nena', 'Navarro', 'Santos', 'Jr.',
    date '1947-12-03', 'FEMALE', 'WIDOWED',
    '09389735971', 'Purok 1, La Purisima, Nabua, Camarines Sur', 'Purok 1', 'La Purisima',
    'ACTIVE', null, 'SANTOS|NENA|NAVARRO|JR|1947-12-03', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '194 days', now() - interval '7 days'),
  ('NMBR-002521', 'Bernadette', 'Rivera', 'Sarmiento', null,
    date '2008-08-22', 'FEMALE', 'WIDOWED',
    '09528881314', 'Purok 4, San Antonio, Nabua, Camarines Sur', 'Purok 4', 'San Antonio',
    'ACTIVE', null, 'SARMIENTO|BERNADETTE|RIVERA||2008-08-22', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '3 days', now() - interval '15 days'),
  ('NMBR-002522', 'Evelyn', 'Castillo', 'Imperial', null,
    date '2022-07-10', 'FEMALE', 'SINGLE',
    '09829610810', 'Purok 4, La Purisima, Nabua, Camarines Sur', 'Purok 4', 'La Purisima',
    'ACTIVE', null, 'IMPERIAL|EVELYN|CASTILLO||2022-07-10', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '153 days', now() - interval '24 days'),
  ('NMBR-002523', 'Gloria', 'Velasco', 'Fernandez', null,
    date '1950-03-01', 'FEMALE', 'SINGLE',
    '09206554781', 'Purok 7, San Antonio, Nabua, Camarines Sur', 'Purok 7', 'San Antonio',
    'ACTIVE', null, 'FERNANDEZ|GLORIA|VELASCO||1950-03-01', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '74 days', now() - interval '9 days'),
  ('NMBR-002524', 'Jocelyn', 'Imperial', 'Gumabao', null,
    date '1970-09-25', 'FEMALE', 'MARRIED',
    '09713956341', 'Sitio Balongay, San Juan, Nabua, Camarines Sur', 'Sitio Balongay', 'San Juan',
    'ACTIVE', null, 'GUMABAO|JOCELYN|IMPERIAL||1970-09-25', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '350 days', now() - interval '8 days'),
  ('NMBR-002525', 'Divina', 'Cruz', 'Aquino', null,
    date '1937-04-26', 'FEMALE', 'SINGLE',
    '09815314493', 'Purok 7, La Purisima, Nabua, Camarines Sur', 'Purok 7', 'La Purisima',
    'ACTIVE', null, 'AQUINO|DIVINA|CRUZ||1937-04-26', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '234 days', now() - interval '8 days'),
  ('NMBR-002526', 'Divina', 'Mercado', 'Cordial', 'Sr.',
    date '1979-03-08', 'FEMALE', 'MARRIED',
    '09901728991', 'Sitio Balongay, Sto. Domingo, Nabua, Camarines Sur', 'Sitio Balongay', 'Sto. Domingo',
    'ACTIVE', null, 'CORDIAL|DIVINA|MERCADO|SR|1979-03-08', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '376 days', now() - interval '17 days'),
  ('NMBR-002527', 'Aurora', 'Velasco', 'Velasco', null,
    date '1978-12-17', 'FEMALE', 'MARRIED',
    '09928276301', 'Sitio Balongay, Sagrada Familia, Nabua, Camarines Sur', 'Sitio Balongay', 'Sagrada Familia',
    'ACTIVE', null, 'VELASCO|AURORA|VELASCO||1978-12-17', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '173 days', now() - interval '8 days'),
  ('NMBR-002528', 'Wilfredo', 'Cruz', 'Ramos', null,
    null, 'MALE', 'MARRIED',
    '605-148', 'Sitio Balongay, Sagrada Familia, Nabua, Camarines Sur', 'Sitio Balongay', 'Sagrada Familia',
    'ACTIVE', null, 'RAMOS|WILFREDO|CRUZ||', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '291 days', now() - interval '22 days'),
  ('NMBR-002529', 'Rene', 'Bonaobra', 'Gonzales', 'Jr.',
    date '1966-03-04', 'MALE', 'WIDOWED',
    '09164148658', 'Purok 7, San Juan, Nabua, Camarines Sur', 'Purok 7', 'San Juan',
    'ACTIVE', null, 'GONZALES|RENE|BONAOBRA|JR|1966-03-04', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '165 days', now() - interval '24 days'),
  ('NMBR-002530', 'Sheila', null, 'Castillo', 'III',
    date '1935-10-14', 'FEMALE', 'SINGLE',
    '09264764916', 'Purok 3, San Juan, Nabua, Camarines Sur', 'Purok 3', 'San Juan',
    'ACTIVE', null, 'CASTILLO|SHEILA||III|1935-10-14', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '216 days', now() - interval '10 days'),
  ('NMBR-002531', 'Carlos', 'Cruz', 'Albao', null,
    date '1950-12-02', 'MALE', 'SINGLE',
    '09276936201', 'Sitio Iraya, San Juan, Nabua, Camarines Sur', 'Sitio Iraya', 'San Juan',
    'ACTIVE', null, 'ALBAO|CARLOS|CRUZ||1950-12-02', true,
    'liza.mercado@nabua.gov.ph', now() - interval '514 days', now() - interval '28 days'),
  ('NMBR-002532', 'Ana', 'Bonaobra', 'Bermudo', 'Sr.',
    date '1966-04-15', 'FEMALE', 'MARRIED',
    '09796468343', 'Purok 5, Santa Cruz, Nabua, Camarines Sur', 'Purok 5', 'Santa Cruz',
    'ACTIVE', null, 'BERMUDO|ANA|BONAOBRA|SR|1966-04-15', true,
    'liza.mercado@nabua.gov.ph', now() - interval '530 days', now() - interval '19 days'),
  ('NMBR-002533', 'Alvin', null, 'Baldovino', null,
    date '1985-01-22', 'MALE', 'SINGLE',
    '09884065890', 'Purok 5, San Rafael, Nabua, Camarines Sur', 'Purok 5', 'San Rafael',
    'ACTIVE', null, 'BALDOVINO|ALVIN|||1985-01-22', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '209 days', now() - interval '27 days'),
  ('NMBR-002534', 'Juan', 'Gonzales', 'Marquez', null,
    date '1960-03-25', 'MALE', 'MARRIED',
    '09973590162', 'Sitio Ilawod, San Juan, Nabua, Camarines Sur', 'Sitio Ilawod', 'San Juan',
    'ACTIVE', null, 'MARQUEZ|JUAN|GONZALES||1960-03-25', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '345 days', now() - interval '20 days'),
  ('NMBR-002535', 'Jose', 'Bermudo', 'Ramos', 'Jr.',
    date '1934-09-23', 'MALE', 'WIDOWED',
    '09854907333', 'Sitio Balongay, San Isidro, Nabua, Camarines Sur', 'Sitio Balongay', 'San Isidro',
    'ACTIVE', null, 'RAMOS|JOSE|BERMUDO|JR|1934-09-23', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '151 days', now() - interval '12 days'),
  ('NMBR-002536', 'Maria', null, 'Nacario', null,
    date '2013-04-25', 'FEMALE', 'SINGLE',
    '09589016892', 'Purok 5, San Antonio, Nabua, Camarines Sur', 'Purok 5', 'San Antonio',
    'ACTIVE', null, 'NACARIO|MARIA|||2013-04-25', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '483 days', now() - interval '11 days'),
  ('NMBR-002537', 'Rogelio', 'Gonzales', 'Ocampo', null,
    date '1998-10-05', 'MALE', 'SINGLE',
    '09699658799', 'Sitio Balongay, San Juan, Nabua, Camarines Sur', 'Sitio Balongay', 'San Juan',
    'ACTIVE', null, 'OCAMPO|ROGELIO|GONZALES||1998-10-05', true,
    'liza.mercado@nabua.gov.ph', now() - interval '238 days', now() - interval '28 days'),
  ('NMBR-002538', 'Aurora', 'Imperial', 'Halcon', null,
    date '2004-06-03', 'FEMALE', 'WIDOWED',
    '09652152386', 'Purok 3, La Purisima, Nabua, Camarines Sur', 'Purok 3', 'La Purisima',
    'ACTIVE', null, 'HALCON|AURORA|IMPERIAL||2004-06-03', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '464 days', now() - interval '16 days'),
  ('NMBR-002539', 'Mark', 'Ramos', 'Marquez', 'Sr.',
    date '2018-07-02', 'MALE', 'SINGLE',
    null, 'Sitio Balongay, Sagrada Familia, Nabua, Camarines Sur', 'Sitio Balongay', 'Sagrada Familia',
    'ACTIVE', null, 'MARQUEZ|MARK|RAMOS|SR|2018-07-02', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '441 days', now() - interval '1 days'),
  ('NMBR-002540', 'Pedro', null, 'Ramos', null,
    date '1986-12-28', 'MALE', 'SINGLE',
    null, 'Purok 1, San Roque, Nabua, Camarines Sur', 'Purok 1', 'San Roque',
    'ACTIVE', null, 'RAMOS|PEDRO|||1986-12-28', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '57 days', now() - interval '5 days'),
  ('NMBR-002541', 'Arlene', 'Padilla', 'Bonaobra', null,
    date '2010-04-13', 'FEMALE', 'SINGLE',
    '09732414881', 'Sitio Ilawod, San Antonio, Nabua, Camarines Sur', 'Sitio Ilawod', 'San Antonio',
    'ACTIVE', null, 'BONAOBRA|ARLENE|PADILLA||2010-04-13', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '241 days', now() - interval '27 days'),
  ('NMBR-002542', 'Mark', 'Mercado', 'Isidro', null,
    date '1946-12-25', 'MALE', 'SINGLE',
    '09591089989', 'Sitio Balongay, San Pedro, Nabua, Camarines Sur', 'Sitio Balongay', 'San Pedro',
    'ACTIVE', null, 'ISIDRO|MARK|MERCADO||1946-12-25', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '463 days', now() - interval '14 days'),
  ('NMBR-002543', 'Eduardo', null, 'Bautista', 'Sr.',
    date '2007-01-23', 'MALE', 'SINGLE',
    '09812559177', 'Sitio Balongay, San Nicolas, Nabua, Camarines Sur', 'Sitio Balongay', 'San Nicolas',
    'ACTIVE', null, 'BAUTISTA|EDUARDO||SR|2007-01-23', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '464 days', now() - interval '28 days'),
  ('NMBR-002544', 'Fernando', 'Salvador', 'Albao', null,
    date '1973-02-12', 'MALE', 'MARRIED',
    '09376583914', 'Purok 1, San Roque, Nabua, Camarines Sur', 'Purok 1', 'San Roque',
    'ACTIVE', null, 'ALBAO|FERNANDO|SALVADOR||1973-02-12', true,
    'liza.mercado@nabua.gov.ph', now() - interval '356 days', now() - interval '15 days'),
  ('NMBR-002545', 'Editha', null, 'Aquino', 'Sr.',
    date '1985-08-18', 'FEMALE', 'WIDOWED',
    '09718694280', 'Purok 3, San Pedro, Nabua, Camarines Sur', 'Purok 3', 'San Pedro',
    'ACTIVE', null, 'AQUINO|EDITHA||SR|1985-08-18', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '155 days', now() - interval '8 days'),
  ('NMBR-002546', 'Alfredo', null, 'Aquino', null,
    date '2013-10-04', 'MALE', 'SINGLE',
    '167-279', 'Sitio Balongay, San Miguel, Nabua, Camarines Sur', 'Sitio Balongay', 'San Miguel',
    'ACTIVE', null, 'AQUINO|ALFREDO|||2013-10-04', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '166 days', now() - interval '6 days'),
  ('NMBR-002547', 'Antonio', null, 'Fabregas', null,
    date '1952-09-05', 'MALE', 'SINGLE',
    null, 'Purok 1, San Isidro, Nabua, Camarines Sur', 'Purok 1', 'San Isidro',
    'ACTIVE', null, 'FABREGAS|ANTONIO|||1952-09-05', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '480 days', now() - interval '27 days'),
  ('NMBR-002548', 'Chona', 'Imperial', 'Reyes', 'Sr.',
    date '1983-07-18', 'FEMALE', 'SINGLE',
    '09238233764', 'Sitio Ilawod, San Juan, Nabua, Camarines Sur', 'Sitio Ilawod', 'San Juan',
    'ACTIVE', null, 'REYES|CHONA|IMPERIAL|SR|1983-07-18', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '540 days', now() - interval '12 days'),
  ('NMBR-002549', 'Chona', 'Velasco', 'Ocampo', null,
    date '1989-07-07', 'FEMALE', 'MARRIED',
    '09518557954', 'Purok 4, San Nicolas, Nabua, Camarines Sur', 'Purok 4', 'San Nicolas',
    'ACTIVE', null, 'OCAMPO|CHONA|VELASCO||1989-07-07', true,
    'liza.mercado@nabua.gov.ph', now() - interval '57 days', now() - interval '17 days'),
  ('NMBR-002550', 'Chona', 'Arellano', 'Fernandez', null,
    null, 'FEMALE', 'SINGLE',
    '09955172578', 'Purok 5, San Rafael, Nabua, Camarines Sur', 'Purok 5', 'San Rafael',
    'ACTIVE', null, 'FERNANDEZ|CHONA|ARELLANO||', true,
    'liza.mercado@nabua.gov.ph', now() - interval '231 days', now() - interval '1 days'),
  ('NMBR-002551', 'Arnold', 'Villanueva', 'Velasco', null,
    date '2021-05-24', 'MALE', 'SINGLE',
    '09914380521', 'Sitio Iraya, San Antonio, Nabua, Camarines Sur', 'Sitio Iraya', 'San Antonio',
    'ACTIVE', null, 'VELASCO|ARNOLD|VILLANUEVA||2021-05-24', true,
    'liza.mercado@nabua.gov.ph', now() - interval '511 days', now() - interval '26 days'),
  ('NMBR-002552', 'Teresita', 'Navarro', 'Dacillo', null,
    date '2013-08-22', 'FEMALE', 'SINGLE',
    '09237223553', 'Sitio Balongay, San Antonio, Nabua, Camarines Sur', 'Sitio Balongay', 'San Antonio',
    'ACTIVE', null, 'DACILLO|TERESITA|NAVARRO||2013-08-22', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '173 days', now() - interval '16 days'),
  ('NMBR-002553', 'Eduardo', 'Fernandez', 'Aquino', null,
    date '1944-05-18', 'MALE', 'MARRIED',
    '09523563390', 'Purok 4, Sagrada Familia, Nabua, Camarines Sur', 'Purok 4', 'Sagrada Familia',
    'ACTIVE', null, 'AQUINO|EDUARDO|FERNANDEZ||1944-05-18', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '0 days', now() - interval '22 days'),
  ('NMBR-002554', 'Rodolfo', 'Cruz', 'Dela Cruz', null,
    date '1983-02-10', 'MALE', 'SINGLE',
    '09875087728', 'Sitio Iraya, San Nicolas, Nabua, Camarines Sur', 'Sitio Iraya', 'San Nicolas',
    'INACTIVE', null, 'DELA CRUZ|RODOLFO|CRUZ||1983-02-10', true,
    'liza.mercado@nabua.gov.ph', now() - interval '107 days', now() - interval '2 days'),
  ('NMBR-002555', 'Juan', 'Santos', 'Dela Cruz', null,
    date '1985-01-12', 'MALE', 'MARRIED',
    '09171234567', 'Purok 3, San Isidro, Nabua, Camarines Sur', 'Purok 3', 'San Isidro',
    'ACTIVE', null, 'DELA CRUZ|JUAN|SANTOS||1985-01-12', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '193 days', now() - interval '9 days'),
  ('NMBR-002556', 'JUAN', 'Santos', 'DELA CRUZ', null,
    date '1985-01-12', 'MALE', 'SINGLE',
    '09171234567', 'Purok 7, San Isidro, Nabua, Camarines Sur', 'Purok 7', 'San Isidro',
    'FOR_REVIEW', 'Verified with barangay records: two different residents share the same name and birthdate.', 'DELA CRUZ|JUAN|SANTOS||1985-01-12#2', false,
    'liza.mercado@nabua.gov.ph', now() - interval '59 days', now() - interval '30 days'),
  ('NMBR-002557', 'Rosario', 'Bautista', 'Navarro', null,
    date '1979-07-04', 'FEMALE', 'MARRIED',
    '09182223333', 'Purok 2, La Purisima, Nabua, Camarines Sur', 'Purok 2', 'La Purisima',
    'ACTIVE', null, 'NAVARRO|ROSARIO|BAUTISTA||1979-07-04', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '367 days', now() - interval '18 days'),
  ('NMBR-002558', 'ROSARIO', 'Bautista', 'NAVARRO', null,
    date '1979-07-04', 'FEMALE', 'SINGLE',
    '09182223333', 'Purok 2, La Purisima, Nabua, Camarines Sur', 'Purok 2', 'La Purisima',
    'FOR_REVIEW', 'Verified with barangay records: two different residents share the same name and birthdate.', 'NAVARRO|ROSARIO|BAUTISTA||1979-07-04#2', false,
    'ana.villanueva@nabua.gov.ph', now() - interval '27 days', now() - interval '17 days'),
  ('NMBR-002559', 'Pedro', null, 'Aquino', null,
    date '1968-11-23', 'MALE', 'MARRIED',
    null, 'Sitio Iraya, San Roque, Nabua, Camarines Sur', 'Sitio Iraya', 'San Roque',
    'ACTIVE', null, 'AQUINO|PEDRO|||1968-11-23', true,
    'liza.mercado@nabua.gov.ph', now() - interval '176 days', now() - interval '11 days'),
  ('NMBR-002560', 'PEDRO', null, 'AQUINO', null,
    date '1968-11-23', 'MALE', 'SINGLE',
    null, 'Sitio Iraya, San Roque, Nabua, Camarines Sur', 'Sitio Iraya', 'San Roque',
    'FOR_REVIEW', 'Verified with barangay records: two different residents share the same name and birthdate.', 'AQUINO|PEDRO|||1968-11-23#2', false,
    'liza.mercado@nabua.gov.ph', now() - interval '26 days', now() - interval '23 days'),
  ('NMBR-002561', 'Marilou', 'Reyes', 'Bermudo', null,
    date '1990-03-18', 'FEMALE', 'MARRIED',
    '09193334444', 'Purok 1, San Antonio, Nabua, Camarines Sur', 'Purok 1', 'San Antonio',
    'ACTIVE', null, 'BERMUDO|MARILOU|REYES||1990-03-18', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '479 days', now() - interval '12 days'),
  ('NMBR-002562', 'MARILOU', 'REYES', 'BERMUDO', null,
    date '1990-03-18', 'FEMALE', 'MARRIED',
    '09193334444', 'Purok 1, San Antonio, Nabua, Camarines Sur', 'Purok 1', 'San Antonio',
    'FOR_REVIEW', 'Flagged during encoding: possible duplicate of an existing master record.', 'BERMUDO|MARILOU|REYES||1990-03-18#2', false,
    'pedro.reyes@nabua.gov.ph', now() - interval '68 days', now() - interval '0 days'),
  ('NMBR-002563', 'Wilfredo', 'Castillo', 'Macatangay', null,
    date '1975-09-02', 'MALE', 'MARRIED',
    null, 'Purok 4, San Juan, Nabua, Camarines Sur', 'Purok 4', 'San Juan',
    'ACTIVE', null, 'MACATANGAY|WILFREDO|CASTILLO||1975-09-02', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '496 days', now() - interval '27 days'),
  ('NMBR-002564', 'Wilfredo  ', 'Castillo', ' Macatangay', null,
    date '1975-09-02', 'MALE', 'MARRIED',
    null, 'Purok 4, San Juan, Nabua, Camarines Sur', 'Purok 4', 'San Juan',
    'FOR_REVIEW', 'Flagged during encoding: possible duplicate of an existing master record.', 'MACATANGAY|WILFREDO|CASTILLO||1975-09-02#2', false,
    'liza.mercado@nabua.gov.ph', now() - interval '4 days', now() - interval '24 days'),
  ('NMBR-002565', 'Rowena', 'Padilla', 'Gumabao', null,
    date '1988-12-12', 'FEMALE', 'MARRIED',
    '09205556666', 'Sitio Ilawod, Santa Cruz, Nabua, Camarines Sur', 'Sitio Ilawod', 'Santa Cruz',
    'ACTIVE', null, 'GUMABAO|ROWENA|PADILLA||1988-12-12', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '371 days', now() - interval '16 days'),
  ('NMBR-002566', 'Rowena', null, 'Gumabao', null,
    date '1988-12-12', 'FEMALE', 'MARRIED',
    '09205556666', 'Sitio Ilawod, Santa Cruz, Nabua, Camarines Sur', 'Sitio Ilawod', 'Santa Cruz',
    'FOR_REVIEW', 'Flagged during encoding: possible duplicate of an existing master record.', 'GUMABAO|ROWENA|||1988-12-12', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '6 days', now() - interval '24 days'),
  ('NMBR-002567', 'Jhun', 'Ocampo', 'Tolentino', null,
    date '1994-06-27', 'MALE', 'MARRIED',
    '09176667777', 'Purok 6, San Miguel, Nabua, Camarines Sur', 'Purok 6', 'San Miguel',
    'ACTIVE', null, 'TOLENTINO|JHUN|OCAMPO||1994-06-27', true,
    'liza.mercado@nabua.gov.ph', now() - interval '285 days', now() - interval '21 days'),
  ('NMBR-002568', 'Jun', 'Ocampo', 'Tolentino', null,
    date '1994-06-27', 'MALE', 'MARRIED',
    null, 'Purok 6, San Miguel, Nabua, Camarines Sur', 'Purok 6', 'San Miguel',
    'FOR_REVIEW', 'Flagged during encoding: possible duplicate of an existing master record.', 'TOLENTINO|JUN|OCAMPO||1994-06-27', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '66 days', now() - interval '22 days'),
  ('NMBR-002569', 'Bernadette', 'Salvador', 'Albao', null,
    date '1999-02-08', 'FEMALE', 'MARRIED',
    null, 'Purok 2, Sagrada Familia, Nabua, Camarines Sur', 'Purok 2', 'Sagrada Familia',
    'ACTIVE', null, 'ALBAO|BERNADETTE|SALVADOR||1999-02-08', true,
    'liza.mercado@nabua.gov.ph', now() - interval '440 days', now() - interval '20 days'),
  ('NMBR-002570', 'Bernadette', 'Salvador', 'Albao', null,
    null, 'FEMALE', 'MARRIED',
    null, 'Purok 2, Sagrada Familia, Nabua, Camarines Sur', 'Purok 2', 'Sagrada Familia',
    'FOR_REVIEW', 'Flagged during encoding: possible duplicate of an existing master record.', 'ALBAO|BERNADETTE|SALVADOR||', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '39 days', now() - interval '19 days'),
  ('NMBR-002571', 'Antonio', 'Rivera', 'Fernandez', null,
    date '1965-04-14', 'MALE', 'MARRIED',
    null, 'Purok 5, San Rafael, Nabua, Camarines Sur', 'Purok 5', 'San Rafael',
    'FOR_REVIEW', null, 'FERNANDEZ|ANTONIO|RIVERA||1965-04-14', true,
    'ana.villanueva@nabua.gov.ph', now() - interval '649 days', now() - interval '17 days'),
  ('NMBR-002572', 'Antonio', 'Rivera', 'Fernandez', null,
    date '1971-08-30', 'MALE', 'MARRIED',
    null, 'Purok 5, San Rafael, Nabua, Camarines Sur', 'Purok 5', 'San Rafael',
    'FOR_REVIEW', 'Possible duplicate raised during encoding.', 'FERNANDEZ|ANTONIO|RIVERA||1971-08-30', true,
    'liza.mercado@nabua.gov.ph', now() - interval '45 days', now() - interval '17 days'),
  ('NMBR-002573', 'Cristina', 'Domingo', 'Isidro', null,
    date '1983-01-05', 'FEMALE', 'MARRIED',
    null, 'Purok 3, Sto. Domingo, Nabua, Camarines Sur', 'Purok 3', 'Sto. Domingo',
    'FOR_REVIEW', null, 'ISIDRO|CRISTINA|DOMINGO||1983-01-05', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '514 days', now() - interval '22 days'),
  ('NMBR-002574', 'Cristina', 'Domingo', 'Isidro', null,
    date '1983-01-05', 'FEMALE', 'MARRIED',
    null, 'Purok 1, San Pedro, Nabua, Camarines Sur', 'Purok 1', 'San Pedro',
    'FOR_REVIEW', 'Possible duplicate raised during encoding.', 'ISIDRO|CRISTINA|DOMINGO||1983-01-05#2', false,
    'pedro.reyes@nabua.gov.ph', now() - interval '8 days', now() - interval '16 days'),
  ('NMBR-002575', 'Rene', 'Velasco', 'Cordial', null,
    date '2001-10-19', 'MALE', 'MARRIED',
    null, 'Sitio Balongay, San Nicolas, Nabua, Camarines Sur', 'Sitio Balongay', 'San Nicolas',
    'FOR_REVIEW', null, 'CORDIAL|RENE|VELASCO||2001-10-19', true,
    'pedro.reyes@nabua.gov.ph', now() - interval '493 days', now() - interval '15 days'),
  ('NMBR-002576', 'Rene', null, 'Cordial', null,
    date '2001-10-19', 'MALE', 'MARRIED',
    null, 'Purok 2, San Nicolas, Nabua, Camarines Sur', 'Purok 2', 'San Nicolas',
    'FOR_REVIEW', 'Possible duplicate raised during encoding.', 'CORDIAL|RENE|||2001-10-19', true,
    'liza.mercado@nabua.gov.ph', now() - interval '23 days', now() - interval '19 days')
) as v(reference_no, first_name, middle_name, last_name, suffix, date_of_birth, sex, civil_status,
       contact_number, address, purok, barangay_name, status, remarks, identity_key, identity_lock,
       encoder_email, created_at, updated_at)
join barangays b on b.name = v.barangay_name
left join users u on u.email = v.encoder_email
where not exists (select 1 from persons p where p.reference_no = v.reference_no);

-- 5. Current barangay history for every member
insert into member_barangay_history (person_id, barangay_id, effective_from, status, reason)
select p.id, p.barangay_id, p.created_at::date, 'ACTIVE', null
from persons p
where p.barangay_id is not null
  and not exists (select 1 from member_barangay_history h where h.person_id = p.id);

-- 6. Sample transfers — a person keeps ONE master record while the barangay changes
-- transfer 1: Rowena Villanueva — San Isidro → San Roque (RESIDENT_TRANSFER)
update member_barangay_history h
   set effective_to = greatest(current_date - interval '120 days', effective_from),
       status = 'ENDED'
 where h.person_id = (select id from persons where reference_no = 'NMBR-002417')
   and h.effective_to is null;

insert into member_barangay_history (person_id, barangay_id, effective_from, status, reason, notes)
select p.id, b.id, current_date - interval '120 days', 'ACTIVE', 'RESIDENT_TRANSFER', 'Family relocated to San Roque.'
from persons p, barangays b
where p.reference_no = 'NMBR-002417' and b.name = 'San Roque';

update persons set barangay_id = (select id from barangays where name = 'San Roque')
 where reference_no = 'NMBR-002417';

-- transfer 2: Danilo Sarmiento — San Juan → Santa Cruz (RESIDENT_TRANSFER)
update member_barangay_history h
   set effective_to = greatest(current_date - interval '210 days', effective_from),
       status = 'ENDED'
 where h.person_id = (select id from persons where reference_no = 'NMBR-002420')
   and h.effective_to is null;

insert into member_barangay_history (person_id, barangay_id, effective_from, status, reason, notes)
select p.id, b.id, current_date - interval '210 days', 'ACTIVE', 'RESIDENT_TRANSFER', 'Moved after marriage.'
from persons p, barangays b
where p.reference_no = 'NMBR-002420' and b.name = 'Santa Cruz';

update persons set barangay_id = (select id from barangays where name = 'Santa Cruz')
 where reference_no = 'NMBR-002420';

-- transfer 3: Evelyn Fernandez — San Miguel → La Purisima (ADMINISTRATIVE_CORRECTION)
update member_barangay_history h
   set effective_to = greatest(current_date - interval '30 days', effective_from),
       status = 'ENDED'
 where h.person_id = (select id from persons where reference_no = 'NMBR-002425')
   and h.effective_to is null;

insert into member_barangay_history (person_id, barangay_id, effective_from, status, reason, notes)
select p.id, b.id, current_date - interval '30 days', 'ACTIVE', 'ADMINISTRATIVE_CORRECTION', 'Corrected barangay assignment — encoded to the wrong barangay.'
from persons p, barangays b
where p.reference_no = 'NMBR-002425' and b.name = 'La Purisima';

update persons set barangay_id = (select id from barangays where name = 'La Purisima')
 where reference_no = 'NMBR-002425';

-- 7. Duplicate cases (pending and resolved history)
insert into duplicate_cases (person_id_a, person_id_b, match_score, match_band, matching_fields,
                             status, source, notes, resolution, reviewed_by_name, reviewed_at)
select a.id, b.id, v.score, v.band::match_band, v.fields, v.status::duplicate_status, v.source,
       v.notes, v.resolution, v.reviewed_by,
       case when v.reviewed_days_ago is null then null else now() - (v.reviewed_days_ago || ' days')::interval end
from (values
  ('NMBR-002555', 'NMBR-002556', 100, 'VERY_LIKELY', '{last_name,first_name,middle_name,date_of_birth,sex}'::text[], 'PENDING', 'LIVE_CHECK', 'Automatically queued: identical identity key accepted with an explicit override. Verify that these are genuinely two different residents.', null, null, null),
  ('NMBR-002557', 'NMBR-002558', 100, 'VERY_LIKELY', '{last_name,first_name,middle_name,date_of_birth,sex}'::text[], 'PENDING', 'LIVE_CHECK', 'Automatically queued: identical identity key accepted with an explicit override. Verify that these are genuinely two different residents.', null, null, null),
  ('NMBR-002559', 'NMBR-002560', 100, 'VERY_LIKELY', '{last_name,first_name,middle_name,date_of_birth,sex}'::text[], 'PENDING', 'LIVE_CHECK', 'Automatically queued: identical identity key accepted with an explicit override. Verify that these are genuinely two different residents.', null, null, null),
  ('NMBR-002561', 'NMBR-002562', 98, 'POSSIBLE', '{last_name,first_name,date_of_birth,sex,barangay}'::text[], 'PENDING', 'LIVE_CHECK', 'Different capitalisation only — same person encoded twice.', null, null, null),
  ('NMBR-002563', 'NMBR-002564', 98, 'POSSIBLE', '{last_name,first_name,date_of_birth,sex,barangay}'::text[], 'PENDING', 'LIVE_CHECK', 'Extra spaces in the encoded name.', null, null, null),
  ('NMBR-002565', 'NMBR-002566', 98, 'POSSIBLE', '{last_name,first_name,date_of_birth,sex,barangay}'::text[], 'PENDING', 'LIVE_CHECK', 'Middle name missing on the second encoding.', null, null, null),
  ('NMBR-002567', 'NMBR-002568', 98, 'POSSIBLE', '{last_name,first_name,date_of_birth,sex,barangay}'::text[], 'PENDING', 'LIVE_CHECK', 'First-name spelling variation (Jhun / Jun).', null, null, null),
  ('NMBR-002569', 'NMBR-002570', 98, 'POSSIBLE', '{last_name,first_name,date_of_birth,sex,barangay}'::text[], 'PENDING', 'LIVE_CHECK', 'Birthdate missing on the second encoding — needs verification, not automatic merging.', null, null, null),
  ('NMBR-002571', 'NMBR-002572', 68, 'POTENTIAL', '{last_name,first_name}'::text[], 'PENDING', 'MANUAL', 'Same name, different birthdate — likely father and son.', null, null, null),
  ('NMBR-002573', 'NMBR-002574', 74, 'POTENTIAL', '{last_name,first_name}'::text[], 'PENDING', 'MANUAL', 'Same name and birthdate but different barangay — verify residency before merging.', null, null, null),
  ('NMBR-002575', 'NMBR-002576', 68, 'POTENTIAL', '{last_name,first_name}'::text[], 'PENDING', 'MANUAL', 'Same name and birthdate, no middle name on record B — check with the household.', null, null, null),
  ('NMBR-002418', 'NMBR-002429', 70, 'POTENTIAL', '{last_name,first_name}'::text[], 'DIFFERENT_PERSON', 'MANUAL', 'Household interview confirmed two different residents.', 'DIFFERENT_PERSON', 'Josefina Ramos', 33),
  ('NMBR-002420', 'NMBR-002431', 76, 'POSSIBLE', '{last_name,first_name}'::text[], 'MERGED', 'MANUAL', 'Same person encoded twice by two encoders.', 'MERGED', 'Maria Santos', 51),
  ('NMBR-002422', 'NMBR-002433', 82, 'POTENTIAL', '{last_name,first_name}'::text[], 'KEPT_BOTH', 'MANUAL', 'Siblings with identical names; both retained deliberately.', 'KEEP_BOTH', 'Josefina Ramos', 59),
  ('NMBR-002424', 'NMBR-002435', 88, 'POSSIBLE', '{last_name,first_name}'::text[], 'DEFERRED', 'MANUAL', 'Waiting for the barangay secretary to confirm residency.', 'DEFER', 'Maria Santos', 18)
) as v(ref_a, ref_b, score, band, fields, status, source, notes, resolution, reviewed_by, reviewed_days_ago)
join persons a on a.reference_no = v.ref_a
join persons b on b.reference_no = v.ref_b
on conflict do nothing;

-- 8. Opening audit trail
insert into audit_logs (user_id, user_name, user_role, action, entity_type, entity_label, reason, new_values, session_info, timestamp)
select u.id, u.name, u.role, 'IMPORTED', 'IMPORT_BATCH', 'nmbr_demo_dataset.csv',
       'Initial municipal registry load', jsonb_build_object('imported', 160), fn_session_info(),
       now() - interval '30 days'
from users u where u.email = 'admin@nabua.gov.ph';
